### ISSUE TITLE
Get-CSObject failed to return result if CN contanins "&"

### ISSUE THREAD

**Issue by kcheng-didata** [lithnet/miis-powershell#11]
Hi Ryan,
I recently experienced an issue when I was searching for a CSObject which has a symbol "&" in the CN. The result returned nothing. But if I use the console, it finds the object.
Can you please check this?
Thanks,
Kevin

**Comment by ryannewington** [comment]
Hi @kcheng-didata,

Can you confirm the command that are you using for me, just so I look in the correct place

Ryan

**Comment by ryannewington** [comment]
Hi @kcheng-didata,

I was able to reproduce it. Please confirm the current build fixes the issue you were seeing.

Cheers,

Ryan

**Comment by kcheng-didata** [comment]
Hi Ryan,

The command I used is similar to below:
Get-CSObject -MA ADMA -RDN "CN=Name & Name"
The param -DN is also having problems too.
Hope this info helps.
Thanks,
Kevin

**Comment by kcheng-didata** [comment]
Hi Ryan,

Thanks very much for the quick response. I just tested the latest release and the issues has been resolved.
Very nice work!
Thanks,
Kevin
