### ISSUE TITLE
Windows SmartScreen blocks release download

### ISSUE THREAD

**Issue by Amethi** [lithnet/miis-powershell#12]
I'm not sure why, but Windows SmartScreen says the https://github.com/lithnet/miis-powershell/releases/download/v1.0.6351/Lithnet.Miiserver.Automation.Setup.msi release is unsafe and won't download (unless you override it).

**Comment by ryannewington** [comment]
Hi Jay,

Thanks for reporting this. I've raised an issue with Microsoft to get this fixed!

Will report back on what they say.

Ryan

**Comment by ryannewington** [comment]
While I didn't hear back from Microsoft, this does seem to be resolved now.
