### ISSUE TITLE
When try to Get-CSObject using -ID, get error of value does not fall within the expected range

### ISSUE THREAD

**Issue by kcheng-didata** [lithnet/miis-powershell#15]
Hi Ryan,
I am getting errors when I try to get csobject by using id. I am not sure if I did something wrong. Below is a sample of a csobject (without DN information for client privacy reason).

ConnectedCSObjects        : {5111c970-121b-e611-80ca-00155d948d09, 4e1da4de-0618-e611-80ca-00155d948d09}
ID                        : 4e1da4de-0618-e611-80ca-00155d948d09
MAID                      : 91bd6acd-c6a9-4340-86b1-0ce6d7805f46
MaName                    : ECD
MvGuid                    : cb861f5d-f655-e511-80c0-00155d948d09
MetaverseLink             : cb861f5d-f655-e511-80c0-00155d948d09

I have tried using every single guid but they all returned error.
PS C:\Users\adm_kcheng> Get-CSObject -id 4e1da4de-0618-e611-80ca-00155d948d09 -ma ecd
Get-CSObject : Value does not fall within the expected range.
At line:1 char:1
+ Get-CSObject -id 4e1da4de-0618-e611-80ca-00155d948d09 -ma ecd
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CSObject], MiiserverException
    + FullyQualifiedErrorId : Lithnet.Miiserver.Client.MiiserverException,Lithnet.Miiserver.Automation.GetCSObject

PS C:\Users\adm_kcheng> Get-CSObject -id cb861f5d-f655-e511-80c0-00155d948d09 -ma ecd
Get-CSObject : Value does not fall within the expected range.
At line:1 char:1
+ Get-CSObject -id cb861f5d-f655-e511-80c0-00155d948d09 -ma ecd
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CSObject], MiiserverException
    + FullyQualifiedErrorId : Lithnet.Miiserver.Client.MiiserverException,Lithnet.Miiserver.Automation.GetCSObject

**Comment by ryannewington** [comment]
@kcheng-didata thanks for reporting this.

It's fixed in the latest build

 https://github.com/lithnet/miis-powershell/releases/tag/v1.0.6429

Please reopen this issue if you still have problems

**Comment by kcheng-didata** [comment]
Hi Ryan,
Yes, I tested and it's working now. Thanks!
