### ISSUE TITLE
Set-MVProvisioningRulesExtension does not manage declarative provisioning

### ISSUE THREAD

**Issue by KentNordstrom** [lithnet/miis-powershell#16]
This Command should support all values corresponding to the mv-data SyncConfig-provisioning-type.
1. "none" = Off
2. "sync-rule" = Synchronization Rule Provisioning is ON
3. "scripted" = Enable Provisioning Rules Provisioning is ON
4. "both" = 2+3 is ON

I usually manage this using the FIMService mv-data object, but this has been declared as a deprecated feature and I need to start using alternative (WMI?) method to turn declarative provisioning on/off.

**Comment by ryannewington** [comment]
My Set-MVProvisioningRulesExtension cmdlet is just a convenience wrapper for this one from Microsoft

https://docs.microsoft.com/en-us/powershell/module/microsoft.directoryservices.metadirectoryservices.config/Set-ProvisioningRulesExtension?view=idm-ps-2016sp1

It doesn't expose any other options.

The only way I could see doing it would be to export the MV config, change the value in the XML, and import it again
