### ISSUE TITLE
New-MVQuery only supports 'text' Operators (Equals, Contains, NotContains, IsPresent, IsNotPresent, StartsWith, EndsWith)

### ISSUE THREAD

**Issue by darrenjrobinson** [lithnet/miis-powershell#2]
Awesome tools. Very powerful. 

Please add support for Integer Operators to New-MVQuery.
_GreaterThan | GreaterThanOrEquals | LessThan | LessThanOrEquals_

Also please add the following Operator
_NotEquals_ 

New-MVQuery : Cannot bind parameter 'Operator'. Cannot convert value "notequals" to type 
"Lithnet.Miiserver.Client.MVSearchFilterOperator". Error: "Unable to match the identifier name notequals to a valid 
enumerator name. Specify one of the following enumerator names and try again:
Equals, Contains, NotContains, IsPresent, IsNotPresent, StartsWith, EndsWith"
At line:1 char:52

DR

**Comment by ryannewington** [comment]
Hi Darren,

Thanks for the feedback. I'm glad your finding the tools useful.  

I'd love to add support for those, and I agree it feels like a big omission. But we are limited by the options presented by the sync engine. Basically what you see in the UI is all I can expose via PowerShell, as we share the same underlying library.

![image](https://cloud.githubusercontent.com/assets/17229877/16940865/e4ccd690-4dcf-11e6-8052-614d762865b2.png)

If someone requests a feature change from Microsoft and they add it in as a UI option, I can expose it using the PowerShell module.

Ryan
