### ISSUE TITLE
Request: Ability to "Refresh Interfaces" on an ECMA2 connector

### ISSUE THREAD

**Issue by kcrosby** [lithnet/miis-powershell#21]
If possible, it would great if there were a PS way to "Refresh Interfaces" on an ECMA2 connector.  Would be a huge help as it could be put into a post-build script in VS.

**Comment by ryannewington** [comment]
@kcrosby I totally agree, I would use this myself in automated builds. Unfortunately the refresh interfaces command expects the UI to be shown and ma data to be provided back. There is a bit more that goes on behind the scenes than appears. As this process and data format isn't documented, it's too risky to try and include. :(
