### ISSUE TITLE
Get-MAStatistic return wrong numbers from Full Import

### ISSUE THREAD

**Issue by blissett** [lithnet/miis-powershell#23]
I've an issue regarding a numbers of Adds I've in a full import.

MIM Reports no adds
![fullimport](https://user-images.githubusercontent.com/8299096/58538945-8d0eb500-81f6-11e9-998e-3c79e687f7c6.PNG)

Get-MaStatistic returns 1 Add (It remember the last value)
PS C:\Windows\system32> $maSNOW = Get-ManagementAgent "SNOW CONSULENTI" -Reload
PS C:\Windows\system32> Start-ManagementAgent -RunProfileName "Full Import" -ma $maSNOW -ErrorAction Stop
PS C:\Windows\system32> $LastImport = Get-MAStatistics -ma $maSNOW
PS C:\Windows\system32> $LastImport
Total                 : 9
TotalConnectors       : 8
TotalDisconnectors    : 1
Placeholders          : 0
NormalConnectors      : 8
ExplicitConnectors    : 0
NormalDisconnectors   : 1
ExplicitDisconnectors : 0
FilteredDisconnectors : 0
ImportAdds            : 1
ImportUpdates         : 1
ImportDeletes         : 0
ImportUnchanged       : 7
PendingImportTotal    : 2
ExportAdds            : 0
ExportUpdates         : 0
ExportDeletes         : 0
PendingExportTotal    : 0

I restart MIMService and Entire Server but Issue Remains..

**Comment by blissett** [comment]
I discovered an uxecepted error on imported object sync, that prevent the numbers of add in Powershell result. I check on SQL Database for the run history and the importdAdds is corret = 0, Maybe If is possible investigate why the powershell returns the Disconnected object in count.

**Comment by ryannewington** [comment]
Hi @blissett,

It's important to note that we are looking at two different things here. The run history is showing you the results of the last run. The statistics are showing you the state of the connector space.

Could it be that the 'add' was imported in a previous run and not yet synchronized? The fact that the stats show 'PendingImportTotal: 2' leads me to believe there is an unsynchronized change waiting there.

We should be able to look at the connector in the connector space and see what its state is. Or alternetively, export the connector space and see if it matches up with the statistics.

https://social.technet.microsoft.com/wiki/contents/articles/33345.fim2010mim2016-how-to-bulk-export-connector-and-disconnector-status.aspx

Ryan
