### ISSUE TITLE
The term 'export-fimconfig' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by majdandoni** [lithnet/miis-powershell#25]
Hi All,

after applying a patch on the MIM Service, Executing powershell scripts are not working anymore with the following error:

The term 'export-fimconfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. | The term 'export-fimconfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. | The term 'export-fimconfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. | The term 'export-fimconfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. | The term 'export-fimconfig' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Running the scripts form PowerShell ISE works fine, but when it is being kicked in from a MIM portal workflow, the issue above is happening. i can work with you if needed to help troubleshoot and debug.

**Comment by ryannewington** [comment]
@majdandoni export-fimconfig is a Microsoft cmdlet. It's not part of my library. You'll need to open a case with them.
