### ISSUE TITLE
Install MSI / Powershell module to use it with Azure AD Connect

### ISSUE THREAD

**Issue by MS-LUF** [lithnet/miis-powershell#26]
Hello,

I would like to use your powershell module to request metaverse of Azure AD Connect (which is build on FIM for the directory sync part).
I have checked your MSI and it seems you have some hardcoded check to detect the installation of FIM during the MSI Wizard (RegLocator\FimInstallDirFromRegistry).
Is it possible to skip this check officially to install it on an Azure AD Connect server ?
Do you already have tested it in that particular context ?

Thanks for your help,

Kind Regards,

Lucas.

**Comment by MSnandokun** [comment]
Hey Lucas, 
I am just testing the same on an AADC server. is the "MS" on your user name because you are MS internal? Blue Badge? Do you want to reach out on Teams? Fernando.Rivera@microsoft
I think its just installing the module in a win-10 machine when we e work on MV Ext. I just need to recreate the FFIM directory structure and might have to register the DLLs in the AADC server. 
I am testing now. 

Nando

**Comment by MS-LUF** [comment]
Hello Fernando,

I am not a MS employee, I am just using MS- as a prefix because all my github repo published contained Microsoft oriented delivrables, mainly powershell modules.

We can have a chat on teams, I am an office 365 customer so we should be federated.

Lucas.
________________________________
De : Fernando Rivera <notifications@github.com>
Envoyé : mardi 2 juin 2020 19:08
À : lithnet/miis-powershell <miis-powershell@noreply.github.com>
Cc : Lucas Cueff <lucas.cueff@lucas-cueff.com>; Author <author@noreply.github.com>
Objet : Re: [lithnet/miis-powershell] Install MSI / Powershell module to use it with Azure AD Connect (#26)


Hey Lucas,
I am just testing the same on an AADC server. is the "MS" on your user name because you are MS internal? Blue Badge? Do you want to reach out on Teams? Fernando.Rivera@microsoft
I think its just installing the module in a win-10 machine when we e work on MV Ext. I just need to recreate the FFIM directory structure and might have to register the DLLs in the AADC server.
I am testing now.

Nando

**Comment by MSnandokun** [comment]
No worries and nice to “meet” you 😊

I’m working on it in between calls but Ill update if I get it working. I have the modules installed on my dev machine so other than the registry entry that points to the MV it should work. That’s my theory at least 😉.

//FR

**Comment by ryannewington** [comment]
Hey guys

There are changes to the internals of AAD connect that made it not directly compatible with the miis module, hence why the installer block was put in place. I can't remember exactly what they were as it was some time ago.

From memory, the issues aren't insurmountable, but I just haven't had the time to look at it personally. If either of you are up for looking into it, I'm happy to review pull requests.

________________________________

**Comment by MSnandokun** [comment]
Hey Ryan

I’d love to work on this. I’m kind of slammed in 2 projects and working on migrations but I’ll block some time in the calendar next week if I can.

Thanks

Fernando Rivera
________________________________

**Comment by ryannewington** [comment]
That's great. Happy to collaborate and share knowledge. Feel free to reach out when you get going. Can chat on email, teams, slack.
