### ISSUE TITLE
Get-SavedRunHistory returns no objects

### ISSUE THREAD

**Issue by ssg47** [lithnet/miis-powershell#27]
Today, I ran:
`Save-RunHistory -File I:\Scripts\_Investigations\_data\RunHistory_2020.08.17.xml`
which generated a file of around 15 KB.

Then I ran:
`Get-SavedRunHistory -File I:\Scripts\_Investigations\_data\RunHistory_2020.08.17.xml`
and got no results.

I had a nose around in the source for RunDetails.cs in miis-client and then ran this:
`Get-Content -path I:\Scripts\_Investigations\_data\RunHistory_2020.08.17.xml -First 3`
and got these lines:
```xml
	<?xml version="1.0" encoding="utf-8"?>
	<execution-histories>
	  <run-details>
```

I think the issue is in line 108 of [RunDetails.cs](https://github.com/lithnet/miis-client/blob/master/src/Lithnet.Miiserver.Client/Models/RunHistory/RunDetails.cs) where it says:
```cs
foreach (XmlNode node in d.SelectNodes("/execution-histories/run-history/run-details"))
```

---
I'm running the current version of LithnetMiisAutomation:

	PS C:\Windows\system32> Get-Module LithnetMiisAutomation | Select-Object -Property Name,Version

	Name                  Version
	----                  -------
	LithnetMiisAutomation 1.0.6960.34402	

and MIM 4.6.34:

	PS C:\Windows\system32> (Get-Item "C:\Program Files\Microsoft Forefront Identity Manager\2010\Synchronization Service\Bin\miiserver.exe").VersionInfo | Select-O
	bject -Property FileVersion,ProductVersion

	FileVersion ProductVersion
	----------- --------------
	4.6.34.0    4.6.34.0

**Comment by ryannewington** [comment]
@ssg47 Thanks for finding this and providing the detailed report.

I've fixed the underlying issue, released a new version which fixes the issue.

https://github.com/lithnet/miis-powershell/releases/tag/v1.0.7536
