### ISSUE TITLE
Disconnect-CSObject : Exception from HRESULT: 0x80230703

### ISSUE THREAD

**Issue by majdandoni** [lithnet/miis-powershell#29]
Hi,

i'm using the example in the disconnect-csobject page to disconnect an object. when i run the get-csobject it works:

PS E:\FIM> $cs = Get-CSObject -RDN "CN=Andoni\, Majd2" -MA "ADMA"
PS E:\FIM> $cs

ConnectedCSObjectLinks    : {PeopleSoftMA, FIMMA, ADMA}
ConnectedCSObjects        : {bb8da061-5514-eb11-816e-000d3a12abca, b25e089d-5514-eb11-816e-000d3a12abca,
                            b35e089d-5514-eb11-816e-000d3a12abca}
AccountName               :
DN                        : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=xxx,DC=xxx,DC=fim
DomainName                :
FullyQualifiedDomainName  :
ID                        : b35e089d-5514-eb11-816e-000d3a12abca
MAID                      : 289377d4-734f-4621-af2f-090423ba2bb1
MaName                    : ADMA
MvGuid                    : b15e089d-5514-eb11-816e-000d3a12abca
ObjectType                : user
PartitionGuid             : c16d9aab-cdea-4d04-b50d-ed8206d26a0e
PartitionName             : DC=xxx,DC=xxx,DC=fim
PendingRefDelete          : False
SeenByImport              : True
IsConnector               : True
ConnectorState            : Normal
RebuildInProgress         : False
Obsoletion                : True
NeedFullSync              : False
IsPlaceholderParent       : False
IsPlaceholderLink         : False
IsPlaceholderDelete       : False
IsPending                 : True
PendingReferenceRetry     : False
PendingRenameRetry        : False
ImportDeltaOperation      : delete
ExportDeltaOperation      : none
LastImportDeltaTime       : 10/22/2020 11:23:53 AM
LastExportDeltaTime       : 10/22/2020 11:11:47 AM
DisconnectionType         :
DisconnectionID           :
DisconnectionTime         :
MetaverseLink             : b15e089d-5514-eb11-816e-000d3a12abca
UnappliedExportDelta      : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=xxx,DC=xxx,DC=fim
EscrowedExportDelta       : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=xx,DC=xxx,DC=fim
UnconfirmedExportDelta    : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=xxxDC=xxxDC=fim
PendingImportDelta        : CN=Andoni\, Majd2,OU=Employees,OU=User Accounts,DC=xxx,DC=xxx,DC=fim
SynchronizedHologram      : CN=Andoni\, Majd2,OU=Employees,OU=User Accounts,DC=xxxDC=xxxg,DC=fim
UnappliedExportHologram   : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=xxxDC=xxx,DC=fim
EscrowedExportHologram    : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=ixxxDC=xxx,DC=fim
UnconfirmedExportHologram : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=xxxDC=xxx,DC=fim
PendingImportHologram     : CN=Andoni\, Majd2\0ADEL:d0f34618-215d-4650-a9c1-9411503916e4,CN=Deleted
                            Objects,DC=xxxDCxxx,DC=fim

However, when i run the disconect-csobject, i get the following error:
PS E:\FIM> Disconnect-CSObject -CSObject $cs -Explicit

Confirm disconnection
This action will result in the metaverse object being deleted. Continue
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
Disconnect-CSObject : Exception from HRESULT: 0x80230703
At line:1 char:1
+ Disconnect-CSObject -CSObject $cs -Explicit
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Disconnect-CSObject], MiiserverException
    + FullyQualifiedErrorId : Lithnet.Miiserver.Client.MiiserverException,Lithnet.Miiserver.Automation.DisconnectCSObj
   ect

**Comment by ryannewington** [comment]
It may be because you have a provisioning rule that is trying to re-provision the same object. What happens if you try to explicit disconnect it using the MIM UI?

**Comment by majdandoni** [comment]
you can go ahead and close this issue
