### ISSUE TITLE
Can this work on Adconnect?

### ISSUE THREAD

**Issue by turbomcp** [lithnet/miis-powershell#3]
i know theoretically it should work since it based on fim
but the install msi doesn't install because it doesn't find fim
is there away to get the module as standalone?

**Comment by ryannewington** [comment]
Theoretically it would, but I agreed with the product group that I would only release it for FIM/MIM, as they have their own PS module for ad connect. So the installer itself will detect for FIM/MIM before allowing installation.

**Comment by darrenjrobinson** [comment]
So the keywords there are "the installer" right Ryan ;-P

**Comment by ryannewington** [comment]
Yes, only the installer does a check to see if FIM is installed, but I haven't tried using the binaries at all on AAD connect.
