### ISSUE TITLE
Get-PendingExportUpdates and multivalued attribute

### ISSUE THREAD

**Issue by carlchevalier** [lithnet/miis-powershell#31]
Hi,

I am running the Get-PendingExportUpdates cmdlet to get all CS objects that are about to be exported. For each CS, I check the attributes that are about to be modified (need to log before/after modification). One attribute I monitor happens to be a "multivalued" attribute. 
In the exemple shown below, I see that there are changes for that attribute but my problem is that I cannot  tell which entry is a "New" versus a "Delete".

Example:
There is one CS object pending export in MIIS. It shows that the AD GroupPriority attribute has one (1) new entry and one (1) delete:

![image](https://user-images.githubusercontent.com/37671331/104056211-1c938c80-51be-11eb-9ce3-a686ea283e87.png)

In Powershell, when I run:

[DBG]: PS C:\apps\psscripts>>$a = Get-PendingExportUpdates -ma AD -Delta
[DBG]: PS C:\apps\psscripts>> $a[0]

![image](https://user-images.githubusercontent.com/37671331/104056387-68463600-51be-11eb-859b-562c89e6c87b.png)

I see that the changes is with the [GroupPriority] attribute and that two entries are referred but how would I be able to tell if it is a delete or a add. Any way it can be done ?

Thanks!

**Comment by Amethi** [comment]
@ryannewington, I have a very similar question. When inspecting pending exports on a REF MVA, we use the `DNAttributes` property, though drilling down into each MVA value the `Operation` is always 'none', regardless of whether it's a Delete or Add. Is this a limitation of the MIM API or perhaps a bug in the module?

**Comment by ryannewington** [comment]
@Amethi  moving this to #34 as its a separate issue
