### ISSUE TITLE
Operation type of changes to DN attributes incorrectly shows 'none'

### ISSUE THREAD

**Issue by ryannewington** [lithnet/miis-powershell#34]
@ryannewington, I have a very similar question. When inspecting pending exports on a REF MVA, we use the `DNAttributes` property, though drilling down into each MVA value the `Operation` is always 'none', regardless of whether it's a Delete or Add. Is this a limitation of the MIM API or perhaps a bug in the module?

In the sync engine manager, you can see whether it's a add/delete, but not via the module.

_Originally posted by @Amethi in https://github.com/lithnet/miis-powershell/issues/31#issuecomment-821018851_

**Comment by ryannewington** [comment]
@amethi Fixed build is here. Let me know if it resolve the issue you reported.

https://github.com/lithnet/miis-powershell/releases/tag/v1.0.7780

**Comment by Amethi** [comment]
That did the job, thanks Ryan! :)
