### ISSUE TITLE
Get-PendingExports result doesn't clarify what old and new values are

### ISSUE THREAD

**Issue by Amethi** [lithnet/miis-powershell#35]
When running `Get-PendingExports -MA xxx -Delta` and inspecting the `.Attributes["xxx].Values` collection, it's not clear what the old and new values are in an update scenario. I thought there was a convention in use, i.e. first value was old and second value was new, but this isn't the case, sometimes they get reversed and show different to how you view the object in the GUI.

Am I doing anything wrong? Is there a way to determine old and new value?

**Comment by ryannewington** [comment]
You're not doing anything wrong. You've found another bug! Fix coming soon.

**Comment by ryannewington** [comment]
Fixed! https://github.com/lithnet/miis-powershell/releases/tag/v1.0.7783

**Comment by Amethi** [comment]
Thanks again Ryan :) Will test asap.

**Comment by Amethi** [comment]
Did the job, thanks Ryan!
