### ISSUE TITLE
Start-ManagementAgent : The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by dwalter0** [lithnet/miis-powershell#36]
When executing Start-Management "MIM Portal" ExFIFS I get an error "Start-ManagementAgent : The given key was not present the dictionary." It works on other run profiles on that MA and others. Also it does actually start the management agent with that run profile so it functions correctly but throws the error.

**Comment by matthew8gibson** [comment]
I had this issue, also.  Only, when reading this did I notice it was actually running the run profile.  :).  I got the error it just happens after invoking the run profile successfully.   Also, it worked fine in a clean PowerShell session.   It was getting the error in VS Code running interactively (with F8), but with restarting VS Code it runs without error.   It's happened on several different VS Code sessions.  I'll post if I learn more about when it happens.

**Comment by ryannewington** [comment]
Hi guys,

Any chance the MA or run profile was renamed recently with this issue? While the call to start the MA works, the call to get the MA run status fails basically with a 'no much MA/run profile exists with that name' error.

Starting a new powershell session will force a reload of the name cache, which might explain why that resolved the issue for @matthew8gibson

**Comment by dwalter0** [comment]
All I can say is that it did end up being intermittent. I'm not experiencing the issue anymore so I'm not sure what caused it or fixed it. I don't think I changed the name of the MA or run profile at any point but maybe a refresh of the session is what solved it. Not sure but it's working now.

**Comment by matthew8gibson** [comment]
I suspect most of the times it happened to me were when the VS Code session had been open for a long time, but not necessarily with any changes being made to the run profiles.  The exception was this last time, this was likely a new MA and new run profiles that were created since the PowerShell session if VS Code was open.  Thanks.
