### ISSUE TITLE
COM class factory for remote component with CLSID {XXXXXXXXX-8731-4159-8BFF-XXX} from machine MIMServer 

### ISSUE THREAD

**Issue by srinivasyk** [lithnet/miis-powershell#39]
Retrieving the COM class factory for remote component with CLSID {XXXXXXXXX-8731-4159-8BFF-XXX} from machine MIMServer failed due to the following error: 80070005.Getting this error even though service account is part of FIMsyncadmins

Any thoughts please ?
[New Text Document.txt](https://github.com/lithnet/miis-powershell/files/9849173/New.Text.Document.txt)

**Comment by ryannewington** [comment]
@srinivasyk 

I haven't come across this before, but 0x80070005 is definitely an 'Access Denied' error message. Something may be wrong with the FIM permissions or WMI/COM registration

Ryan

**Comment by srinivasyk** [comment]
Thanks @ryannewington for the response .We did some other workaround and didn't have to use Lithnet Module in the end :)
