### ISSUE TITLE
Get-MVObject with multiple queries seem to fail with large result set

### ISSUE THREAD

**Issue by Bob-Bradley** [lithnet/miis-powershell#4]
Hi Ryan.

Loving this library mate!  Using v1.0.6053

I have the following query set:

Attribute        Value    Operator
---------        -----    --------
employeeStatus   active     Equals
sourceForest     NA         Equals
accountName      E      StartsWith
employeeID               IsPresent
assignedLicenses         IsPresent

When I run **Get-MVObject -Queries $queries** I end up with 675 objects and no error.  However when I remove the accountName filter the result should be 2849 objects but instead I get the following exception:

`Get-MVObject : There are multiple root elements. Line 172030, position 2.
At line:9 char:17
+     $mvPeople = Get-MVObject -Queries $queries
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MVObject], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,Lithnet.Miiserver.Automation.GetMVObject`

Is there an undocumented limit for this function?
Thanks.

**Comment by ryannewington** [comment]
Hi Bob,

Can you send me the $stacktrace variable after you get that error?

Cheers

**Comment by ryannewington** [comment]
Never mind I can reproduce it

**Comment by ryannewington** [comment]
Fixed in [v1.0.6065](https://github.com/lithnet/miis-powershell/releases/tag/v1.0.6065)
