### ISSUE TITLE
WTF (where to find) Lithnet.Miiserver.Client

### ISSUE THREAD

**Issue by craig-martin** [lithnet/miis-powershell#5]
Nice work Ryan!  Looks like a really nice job abstracting mmswebservice into nice commands.  Looking at the source I see a reference to Lithnet.Miiserver.Client but don't see that package or source anywhere.  Is it available too?

**Comment by ryannewington** [comment]
Hi Craig, I haven't got around to documenting the public methods yet ,and some of the functions may still change which is the only reason I haven't made it available yet. Happy to provide you with a copy, noting that its subject to change, and you'll have to find your own way through it without doco at this point.

Ryan

**Comment by AndyPowerShell** [comment]
Hi Ryan,

If possible, is there anyway I might be able to get a copy of the latest version of this as well. I am fine with no documentation and subject to change.

Thanks,

Andy

**Comment by ryannewington** [comment]
Hi @AndyPowerShell,

I've made the repository public, with a note that it's currently undocumented and subject to change.

[miis-client](https://github.com/lithnet/miis-client)

Ryan
