### ISSUE TITLE
Add Cmdlets to Remove-MA and support Connector Space Only

### ISSUE THREAD

**Issue by AndySchneiderDev** [lithnet/miis-powershell#6]
For Dev and Test work, I find myself clearing out the CS on my MA's all the time. It would be great if there if there was a Remove-MA Cmdlet that could replicate what this dialog does in the UI.

![image](https://cloud.githubusercontent.com/assets/1766015/18104595/be3d7d5c-6eb0-11e6-9566-9e3598ec7ebd.png)

**Comment by ryannewington** [comment]
At first glance, it looks a bit tricky (there isn't a straightforward call to make), but i'll have a go and see what I come up with
