### ISSUE TITLE
Export-ManagementAgent fails to export MA without error

### ISSUE THREAD

**Issue by darrenjrobinson** [lithnet/miis-powershell#7]
Export-ManagementAgent cmdlet fails to create the requested <ma>.xml file.
If the incorrect MA name is provided the expected error is received.
Have tried full path to intended output file, file only path for the current directory for the output file. 
Verbose provides no additional information. 
Have tried with core MIM MA's (eg. the Out of the Box AD MA), as well as the MIM Service MA and Granfeldt PowerShell MA. 

Can reproduce on MIM 2016 w/ SP1 **4.4.1302.0** and MIM 2016 **4.3.2195.0**

```
PS C:\temp\backup> Export-ManagementAgent -File c:\temp\backup\adusers.xml -MA "AzureADUsers" -Verbose -Debug

PS C:\temp\backup> dir

PS C:\temp\backup> Export-ManagementAgent -File c:\temp\backup\adusers.xml -MA "AzureADUsers2" -Verbose -Debug
Export-ManagementAgent : Management agent AzureADUsers2 was not found
At line:1 char:1
+ Export-ManagementAgent -File c:\temp\backup\adusers.xml -MA "AzureADU ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-ManagementAgent], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Lithnet.Miiserver.Automation.ExportManagementAgent
 

PS C:\temp\backup> Export-ManagementAgent -File adusers.xml -MA "AzureADUsers" -Verbose -Debug

PS C:\temp\backup> dir

PS C:\temp\backup> 
```

**Comment by ryannewington** [comment]
What a useful cmdlet! 

Problem found. Stand by for updated version with fix.

**Comment by ryannewington** [comment]
Updated release and ps gallery binaries.

@darrenjrobinson can you test and let me know if its all ok now?

**Comment by darrenjrobinson** [comment]
Awesome service Ryan. On Australia Day as well.

Confirmed all is 100% working now. Champion. 


```

Import-Module lithnetmiisautomation -RequiredVersion 1.0.6235
$magents = Get-ManagementAgent | select name

foreach ($ma in $magents.name){
    Export-ManagementAgent -File "c:\backup\$ma.xml" -MA $ma 
}
```
