### ISSUE TITLE
Disconnect-CSObject -confirm parameter

### ISSUE THREAD

**Issue by darrenjrobinson** [lithnet/miis-powershell#8]
The Disconnect-CSObject cmdlet requires confirmation for the deletion of the object.
Could we please have a parameter to accept the confirmation so the command can be used programmaticly.

**Comment by ryannewington** [comment]
Thanks @darrenjrobinson - good find.

Adds -Force parameter in commit https://github.com/lithnet/miis-powershell/commit/521b1086aa9229b790fac640918a2478b08e008a

Release: https://github.com/lithnet/miis-powershell/releases/tag/v1.0.6320

**Comment by darrenjrobinson** [comment]
Awesome, thx Ryan. I can retire my Send Enter Key to the Dialog Window loop now 👍  [http://blog.darrenjrobinson.com/an-alternate-method-for-dealing-with-orphaned-metaverse-objects/ ](url)

**Comment by ryannewington** [comment]
Oh dear. Glad you let me know about that!
