### ISSUE TITLE
i wish this could work on aadconnect also(setup blocks it)

### ISSUE THREAD

**Issue by turbomcp** [lithnet/miis-powershell#9]
i wish this could work on aadconnect also(setup blocks it)
we have a lot of orphan objects so this could be amazing:(

**Comment by ryannewington** [comment]
Unfortunately the binaries are different between the two and its not just a matter of unlocking the installer (I have tried it for my own environment). It's not impossible, but not straight forward either. It's something I'd like to look at in the future, but it's not on the plans right now.
